services:
  tailwind:
    build:
      context: .
      dockerfile: dev/tailwind/Dockerfile
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
  templ:
    build:
      context: .
      dockerfile: dev/templ/Dockerfile
    command: >
      --watch --proxy="http://localhost:8080" --proxybind=0.0.0.0
      --proxyport=3000 --cmd="go run cmd/main.go" --open-browser=false
    stop_signal: SIGINT # templ doesn't remove the .txt files without this
    ports:
      - "3000:3000"
    environment:
      - PORT=8080
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes:
      - .:/app
