services:
  app:
    build:
      context: .
      dockerfile: dev/Dockerfile
    platform: linux/amd64
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PORT=3000
